# ─── ADS Frontend — Cloud Build + Cloud Run ──────────────────────────────────
#
# Pre-requisites (run once):
#
# 1. Create Artifact Registry repo:
#    gcloud artifacts repositories create ads \
#      --repository-format=docker --location=europe-west1 \
#      --project=oneline-474118
#
# 2. Store the backend API URL in Secret Manager:
#    echo -n "https://ads-api-<hash>-ew.a.run.app/api" | \
#      gcloud secrets create ADS_API_URL --data-file=- --project=oneline-474118
#
# 3. Grant Cloud Build SA access to the secret:
#    gcloud secrets add-iam-policy-binding ADS_API_URL \
#      --member="serviceAccount:<BUILD_SA>@cloudbuild.gserviceaccount.com" \
#      --role="roles/secretmanager.secretAccessor" --project=oneline-474118
#
# 4. Create a Cloud Build trigger pointing at this repo, branch=main, this file.
# ─────────────────────────────────────────────────────────────────────────────

steps:
  # ── 1. Pull the API URL from Secret Manager ──────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-secrets'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud secrets versions access latest \
          --secret=ADS_API_URL --project=$PROJECT_ID \
          > /workspace/api_url.txt
        echo "API URL: $(cat /workspace/api_url.txt)"

  # ── 2. Build Docker image (pass API URL as build arg) ────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    waitFor: ['get-secrets']
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(cat /workspace/api_url.txt)
        docker build \
          --build-arg EXPO_PUBLIC_API_URL="$API_URL" \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web:$COMMIT_SHA \
          -t europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web:latest \
          .

  # ── 3. Push image ─────────────────────────────────────────────────────────
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    waitFor: ['docker-build']
    args:
      - push
      - '--all-tags'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web'

  # ── 4. Deploy to Cloud Run ────────────────────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'cloud-run-deploy'
    waitFor: ['docker-push']
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ads-web
      - --image=europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web:$COMMIT_SHA
      - --region=europe-west1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --min-instances=0
      - --max-instances=3
      - --memory=256Mi
      - --cpu=1
      - --project=$PROJECT_ID

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web:$COMMIT_SHA'
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/ads/ads-web:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
